on: [push, pull_request]

jobs:
  build-windows-amd64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --build-games=cstrike --prefix=bin
        ./waf.bat install

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: windows-amd64
        path: bin
